### ISSUE TITLE
DownThemAll fork 3.0.9.2 no longer works in SeaMonkey 2.53.13

### ISSUE THREAD

**Issue by Ideficks** [dirkf/downthemall-was-legacy#4]
### Your DownThemAll! and Browser Version and Language and Operating System
- DTA! 3.0.9.2 , SeaMonkey 2.53.13 , de , Win 10

### Expected Behavior
- should work

### Actual Behavior
- don't work at all

### Steps To Reproduce
- install and try

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*
- Diagnostic Logging in the Privacy tab of the DownThemAll! preferences doesn't work either

**Comment by dirkf** [comment]
Did you try https://github.com/dirkf/downthemall-was-legacy/releases/tag/3.1.2?

**Comment by Ideficks** [comment]
> Did you try https://github.com/dirkf/downthemall-was-legacy/releases/tag/3.1.2?
Yes I did. I had read a review on https://addons.thunderbird.net/de/seamonkey/addon/downthemall/reviews/1170112/ and then installed the version 3.1.2. Works like a charm.

**Comment by Ideficks** [comment]
> Did you try https://github.com/dirkf/downthemall-was-legacy/releases/tag/3.1.2?

**Comment by Ideficks** [comment]
> >Did you try https://github.com/dirkf/downthemall-was-legacy/releases/tag/3.1.2?

Yes I did. I had read a review on https://addons.thunderbird.net/de/seamonkey/addon/downthemall/reviews/1170112/ and then installed the version 3.1.2. Works like a charm.
